### PR TITLE
Add alwaysShowTitle property

### PR DESCRIPTION
**Pull request by Drakonov**
## Status

**READY**

## Breaking Changes

NO

## Description

Add alwaysShowTitle property

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [x] 📝 Documentation

### CODE REVIEW

**Comment by Drakonov** [comment]
> ## Status
> **READY**
> 
> ## Breaking Changes
> NO
> 
> ## Description
> Add alwaysShowTitle property
> 
> ## Type of Change
> * [x]  ✨ New feature (non-breaking change which adds functionality)
> * [x]  📝 Documentation

**Comment by divshekhar** [comment]
Hey @Drakonov, the flutter analysis check has failed because of unused import. It is requested to run `flutter analyze --no-pub` and remove the issues. Thank you!

**Comment by Drakonov** [comment]
Thank you for your note, now I corrected and went through `flutter analyze --no-pub`, now it does not give errors

**Comment by divshekhar** [comment]
There are some automated checks:
1. Format - `flutter format --set-exit-if-changed lib`
2. Analyze - `flutter analyze --no-pub`
Please format and analyze, to pass the checks.

**Comment by Drakonov** [comment]
I don't understand why it doesn't pass flutter `format --set-exit-if-changed lib`.

**Comment by Drakonov** [comment]
Just drops the error and that's it.

**Comment by divshekhar** [comment]
The format check failed because the unused import was removed but not the whole line, thus creating a formatting issue.

**Comment by Drakonov** [comment]
That's how it is, now it's more or less clear.

**Comment by Drakonov** [comment]
All checks have passed

**Review by 4-alok — COMMENTED** [review]
Thank you for your contribution; it will be published on pub.dev soon.

**Pull request merged**
